### ISSUE TITLE
Splice lazy sequences in Hiccup vectors

### ISSUE THREAD

**Issue by aperiodic** [lynaghk/singult#10]
Hiccup supports plopping lazy sequences that contain child vectors into a hiccup vector. I think you're aware of the semantics, since you use them in your C2 bullets example. It would be great if Singult supported this as well, so I don't have to do perform unwieldy workarounds with vec and concat. If I try to insert lazy sequences, then `singult.coffee.canonicalize_hiccup` throws an `Uncaught TypeError`, with the message that `Object div.child,[object Object] has no method 'match'`.

**Comment by lynaghk** [comment]
Singult explodes seqs in place (see discussion in the README).
If you think you've found a bug around this behavior, please provide a minimal example and I'll reopen.

**Comment by aperiodic** [comment]
Minimal example here: https://gist.github.com/3390189.

**Comment by lynaghk** [comment]
I threw this into a project I'm working on and everything renders out fine.
You are using C2 0.2.1-SNAPSHOT and there is an div element with id "content" on the page already?

**Comment by aperiodic** [comment]
Oh, I was using `0.2.0` because that's what's in the README. The problem is fixed in the most recent snapshot. Seems like reason enough for a release?

**Comment by aperiodic** [comment]
Sorry, my prior (deleted) comment was incorrect; I can reproduce with `0.2.0`, but not `0.2.1-SNAPSHOT`

**Comment by lynaghk** [comment]
Releasing C2 0.2.1 would require bumping and releasing a number of upstream libs as well (reflex and singult).
We're finishing up two big projects @keminglabs using 0.2.1-SNAPSHOT and I want to keep that version open in case we run into anything else.

C2 0.2.1 will be out in the next fortnight.

**Comment by aperiodic** [comment]
Alright. Will you update the README to recommend the snapshot in the meantime?
