### ISSUE TITLE
Support for attribute namespaces

### ISSUE THREAD

**Issue by Macroz** [lynaghk/singult#14]
singult determines the namespace of a tag, but not the namespace of a tag attribute. This is a problem with XML attributes that also require a specific namespace to work. For example, browsers refuse rendering an svg:image when the href is not from the xlink namespace i.e. <svg:image xlink:href="..." ... /> This of course requires internally parsing the attributes for namespace like with tags and calling setAttributeNS with the proper namespace. Please consider adding this feature.

**Comment by lynaghk** [comment]
I won't be able to get to this anytime soon.
It's a reasonable thing to have in the library though---if you're blocking on having this feature you're welcome to implement and submit a pull.

**Comment by Macroz** [comment]
I got the dev environment setup so I'll see what I can do.
