### ISSUE TITLE
Tag attributes are not rendered.

### ISSUE THREAD

**Issue by soulne4ny** [lynaghk/singult#16]
Hi,

I've found that `render` does not add attrubutes to tags like `hiccup` does.
So the following

```
(singult/render [:div
            {:style "background-color:lightblue"}
            [:h2 {:style "color:green"} "I should be green."]
            [:p {:style "color:orange"} "I should be orange."]
        ]))
```

produces

```
<div><h2>I should be green.</h2><p>I should be orange.</p></div>
```

Do I do smth wrong or it is an error in the library?

Thanks in advance :)

```
  :dependencies [
    [org.clojure/clojure "1.4.0"]
    [com.keminglabs/singult "0.1.5"]]
```

**Comment by lynaghk** [comment]
Singult treats the style property specially and assumes that it'll be passed a map of style properties to values.
This was mentioned in the README, but the markdown formatting was off---I just pushed a fix in 08f698b.
