### ISSUE TITLE
JS version not working properly

### ISSUE THREAD

**Issue by emil0r** [lynaghk/singult#17]
SingultJS.coffee does not appear to have compiled, so the helper functions are not there. Using the singult.coffee namespaced works fine though :).

Really sweet library btw. Having to work with JS it's really nice to have something like this where I can just declare what the HTML is supposed to look like with data structures instead of strings. Big thumbs up!

**Comment by emil0r** [comment]
Never mind. Saw that it was the minified version that had that functionality.

**Comment by lynaghk** [comment]
@emil0r, I haven't been cutting new builds of the JavaScript version, because I didn't know that anyone was using it. Try pulling down the source and building a copy yourself to get the latest. If you run into problems, feel free to open up issues.

**Comment by emil0r** [comment]
It worked. Although I started using the generated JS files from the coffeescript source code directly instead since I use Google Closure for the project anyway.
