### ISSUE TITLE
CLJ Hiccup compatibility layer

### ISSUE THREAD

**Issue by lynaghk** [lynaghk/singult#4]
Singult has some extra sugar to expand `:style` or `:properties` attributes on elements.
This breaks compatibility with JVM Clojure's Hiccup library.

To make sure that templates/markup can be shared between the clientside and serverside, write a fn to walk Singult vectors and expand the sugar into something Hiccup can eat:
- `:style` maps need to be flattened into strings
- `:properties` maps need to be expanded into toplevel attributes (`checked=true`)

**Comment by prabhasp** [comment]
I'm using c2 in a project now to share code between clj and cljs to produce some data visualizations. (Most visualization is done client-side, but some can be also done server-side, eg. for viz embedded in other pages).

A simple thing, ie singult checking the type of the value corresponding to `:style`, leaving it be if it is a string and doing whatever it does when finding an object / map would increase interoperability significantly.

**Comment by lynaghk** [comment]
Since the release of React.js and the various ClojureScript wrappers (Om, Sablono, &c.) I've effectively stopped using Singult.
React is faster, handles far more edge cases, and more featured.

I'm not currently doing any serverside rendering with React, but my feeling is that there may be a Clojure/ClojureScript project that handles it for you.
Alternatively, you may be able to use JDK8's JavaScript engine (nashorn) to use React's pre-rendering pipeline.

**Comment by prabhasp** [comment]
Okay, thanks for letting me know. Ended up here because I was using
`c2/unify`. I suppose I'll change my uses of `unify` into `map`, and then
do conversion to the dom using sablono rather than singult. Thanks!

On Monday, November 3, 2014, Kevin Lynagh notifications@github.com wrote:

> Since the release of React.js and the various ClojureScript wrappers (Om,
> Sablono, &c.) I've effectively stopped using Singult.
> React is faster, handles far more edge cases, and more featured.
> 
> I'm not currently doing any serverside rendering with React, but my
> feeling is that there may be a Clojure/ClojureScript project that handles
> it for you.
> Alternatively, you may be able to use JDK8's JavaScript engine (nashorn)
> to use React's pre-rendering pipeline.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/lynaghk/singult/issues/4#issuecomment-61490934.

## 

Prabhas Pokharel
http://prabhasp.com
twitter/skype/facebook/whatever: prabhasp
