### ISSUE TITLE
Collections are rendered differently than with Hiccup

### ISSUE THREAD

**Issue by emezeske** [lynaghk/singult#5]
Singult renders the following snippet differently than Hiccup:

```
[:span (list "Hello" [:br] "World")]
```

Hiccup:

```
<span>Hello<br>World</span>
```

Singult:

```
<span><hello><br>World</hello></span>
```

Is this the intended behavior?  If so, what kind of singult code would generate output like Hiccup's?

BTW, other than this nit, singult appears to be a drop-in replacement for Crate in my app (at least for rendering; Crate has a bunch of utilities for building Hiccup-style vectors, e.g. crate.element, etc).  Which is pretty cool.

**Comment by lynaghk** [comment]
What version of Singult are you using? I just tried with the 0.1.3-SNAPSHOT and

```
(render [:span "hello" [:br] "world"])
```

yields

```
<span>hello<br>world</span>
```

Also, note that (as in hiccup), all seqs are exploded in place, so `[:span "hello" [:br] "world"]` is equivalent to `[:span (list "hello" [:br] "world")]`.

**Comment by emezeske** [comment]
Thanks.  Ah, I was using 0.1.1.  I should have poked around Clojars for the latest.  Update your README, bro!  :)

Yeah, my example using `(list ...)` was a bit contrived; my real situation is more like `[:span (func-that-returns-list)]`, which it looks like should be fine with 0.1.3-SNAPSHOT.

**Comment by lynaghk** [comment]
v0.1.3 released and readme updated, bro =)

**Comment by emezeske** [comment]
^_^
